
export interface Instrucciones {

  ok: boolean;
  aparatos: [ Aparato ];
}

export interface AparatoRespuesta {
  ok: boolean;
  instrucciones: Aparato;
}

export interface Aparato {
  uid?: string;
  aparato: string;
  descripcion: string;
  video: string;
  imagenes: string;
}

export interface Info {
  id: string;
  descripcion: string[];
  video: string[];
}

// Generated by https://quicktype.io

export interface PisoRespuesta {
  ok: boolean;
  pisoItems: Piso;
}

export interface Piso {
  nombre: string;
  resumen: string;
  descripcion: string;
  video: [
    {
      videoDescripcion: string;
      videoUrl: string;
    }
  ];
}

// Generated by https://quicktype.io

