// Generated by https://quicktype.io

export interface GasolineraRespuesta {
  ok: boolean;
  gasolinera: Gasolineras;
}

export interface GetGasolineras{
  ok: boolean;
  gasolineras: Gasolineras[];
}

export interface Gasolineras {
  uid?: string;
  nombre: string;
  direccion: string;
  poblacion: string;
  pais: string;
  gMaps: string;
  todoElDia: boolean;
}

// Generated by https://quicktype.io

export interface TiendaRespuesta {
  ok: boolean;
  tienda: Tiendas;
}

export interface GetTiendas{
  ok: boolean;
  tiendas: Tiendas[]
}

export interface Tiendas {
  uid?: string;
  nombre: string;
  direccion: string;
  descripcion: string;
  poblacion: string;
  gMaps: string;
}

export interface SaludRespuesta {
  ok: boolean;
  salud: Salud;
}

export interface GetSalud{
  ok: boolean;
  salud: Salud[];
}

export interface Salud {
  uid?: string;
  nombre: string;
  tipo: string;
  direccion: string;
  poblacion: string;
  gMaps: string;
  todoElDia: boolean;
}
