// Generated by https://quicktype.io

export interface GetPlayas {
  ok: boolean;
  playas: Playas[];
}

export interface PlayasRespuesta {
  ok: boolean;
  playas: Playas;
}

export interface Playas {
  uid?: string;
  id: string;
  nombre: string;
  descripcion: string;
  gMaps: string;
  imagen: string;
}
