// Generated by https://quicktype.io

export interface GetRestaurantes {
  ok: boolean;
  restaurantes: Restaurante[];
}

export interface RestauranteRespuesta{
  ok: boolean;
  restaurante: Restaurante;
}


export interface Restaurante {
  uid:           string;
  nombre:       string;
  direccion:    string;
  link:         string;
  descripcion:  string;
  gMaps:        string;
}

