// Generated by https://quicktype.io

export interface Restaurantes {
  restaurantes: Restaurante[];
}

export interface Restaurante {
  nombre:       string;
  direccion:    string;
  link:         string;
  descripcion:  string;
  localizacion: string;
}

