// Generated by https://quicktype.io

export interface Restaurante {
  id:           string;
  nombre:       string;
  direccion:    string;
  link:         string;
  descripcion:  string;
  gMaps:        string;
}

